#!/usr/bin/env ruby
require 'rubygems'
require "daemons"
require "daemons/rails/config"

config = Daemons::Rails::Config.new("openliga_watch", File.dirname(__FILE__) + "/../../")

Daemons.run File.dirname(__FILE__) + "/openliga_watch.rb", config.to_hash